# Generated by Django 3.2.6 on 2021-09-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'InfoS',
            },
        ),
    ]
