# Generated by Django 3.2.5 on 2021-07-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('part time', 'part time'), ('full time', 'full time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
